"""init

Revision ID: a0628bd951ac
Revises: 
Create Date: 2022-07-30 15:54:54.821883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0628bd951ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('rol', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_email'), 'admin', ['email'], unique=True)
    op.create_table('grado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=True),
    sa.Column('año', sa.String(length=4), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alumno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricula', sa.String(length=10), nullable=True),
    sa.Column('nombres', sa.String(length=50), nullable=True),
    sa.Column('apellido_p', sa.String(length=50), nullable=True),
    sa.Column('apellido_m', sa.String(length=50), nullable=True),
    sa.Column('decanato', sa.String(length=50), nullable=True),
    sa.Column('parroquia', sa.String(length=80), nullable=True),
    sa.Column('telefono', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('foto', sa.String(length=120), nullable=True),
    sa.Column('id_grado', sa.Integer(), nullable=True),
    sa.Column('pago', sa.Integer(), nullable=True),
    sa.Column('boleta', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['id_grado'], ['grado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alumno_email'), 'alumno', ['email'], unique=True)
    op.create_table('evaluacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.String(length=50), nullable=True),
    sa.Column('id_alumno', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_alumno'], ['alumno.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evaluacion')
    op.drop_index(op.f('ix_alumno_email'), table_name='alumno')
    op.drop_table('alumno')
    op.drop_table('grado')
    op.drop_index(op.f('ix_admin_email'), table_name='admin')
    op.drop_table('admin')
    # ### end Alembic commands ###
